/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Notas;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitle = new javax.swing.JLabel();
        jLn1 = new javax.swing.JLabel();
        jLn2 = new javax.swing.JLabel();
        jLn3 = new javax.swing.JLabel();
        jLn4 = new javax.swing.JLabel();
        jLn5 = new javax.swing.JLabel();
        jTn1 = new javax.swing.JTextField();
        jTn2 = new javax.swing.JTextField();
        jTn3 = new javax.swing.JTextField();
        jTn4 = new javax.swing.JTextField();
        jTn5 = new javax.swing.JTextField();
        jBcalcular = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jLpromedio = new javax.swing.JLabel();
        jLdesviacion = new javax.swing.JLabel();
        jLnmayor = new javax.swing.JLabel();
        jLnmenor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitle.setText("Notas");

        jLn1.setText("Nota 1:");

        jLn2.setText("Nota 2:");

        jLn3.setText("Nota 3:");

        jLn4.setText("Nota 4:");

        jLn5.setText("Nota 5:");

        jTn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTn4ActionPerformed(evt);
            }
        });

        jBcalcular.setText("Calcular");
        jBcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcalcularActionPerformed(evt);
            }
        });

        jBborrar.setText("Borrar");
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        jLpromedio.setText("Promedio:");

        jLdesviacion.setText("Desviacion estandar:");

        jLnmayor.setText("Nota mayor:");

        jLnmenor.setText("Nota menor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLtitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLn2)
                                .addGap(18, 18, 18)
                                .addComponent(jTn2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLn1)
                                .addGap(18, 18, 18)
                                .addComponent(jTn1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLn3)
                                .addGap(18, 18, 18)
                                .addComponent(jTn3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLn4)
                                .addGap(18, 18, 18)
                                .addComponent(jTn4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLn5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBcalcular)
                                        .addGap(37, 37, 37)
                                        .addComponent(jBborrar))
                                    .addComponent(jTn5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLpromedio)
                                    .addComponent(jLdesviacion)
                                    .addComponent(jLnmayor)
                                    .addComponent(jLnmenor))
                                .addGap(157, 157, 157)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLtitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLn1)
                    .addComponent(jTn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLn2)
                    .addComponent(jTn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLn3)
                    .addComponent(jTn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLn4)
                    .addComponent(jTn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLn5)
                    .addComponent(jTn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcalcular)
                    .addComponent(jBborrar))
                .addGap(18, 18, 18)
                .addComponent(jLpromedio)
                .addGap(18, 18, 18)
                .addComponent(jLdesviacion)
                .addGap(18, 18, 18)
                .addComponent(jLnmayor)
                .addGap(18, 18, 18)
                .addComponent(jLnmenor)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcalcularActionPerformed
        String errorc1 = "";
        String errorc2 = "";
        String errorc3 = "";
        String errorc4 = "";
        String errorc5 = "";
        Boolean errornotas = false;
        double nota1, nota2, nota3, nota4, nota5 = 0;
        try{
        nota1 = Double.parseDouble(jTn1.getText());
        }catch (NumberFormatException a){
            errornotas = true;
            errorc1 = "El valor ingresado en el campo 1 no es valido";
        }       
        if (!errorc1.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, errorc1, "Error", JOptionPane.ERROR_MESSAGE);
            jTn1.setText("");}
        try{
        nota2 = Double.parseDouble(jTn2.getText());
        }catch (NumberFormatException b){
            errornotas = true;
            errorc2 = "El valor ingresado en el campo 2 no es valido";
        }       
        if (!errorc2.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, errorc2, "Error", JOptionPane.ERROR_MESSAGE);
            jTn2.setText("");}
        try{
        nota3 = Double.parseDouble(jTn3.getText());
        }catch (NumberFormatException c){
            errornotas = true;
            errorc3 = "El valor ingresado en el campo 3 no es valido";
        }       
        if (!errorc3.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, errorc3, "Error", JOptionPane.ERROR_MESSAGE);
            jTn3.setText("");}
        try{
        nota4 = Double.parseDouble(jTn4.getText());
        }catch (NumberFormatException d){
            errornotas = true;
            errorc4 = "El valor ingresado en el campo 4 no es valido";
        } 
        if (!errorc4.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, errorc4, "Error", JOptionPane.ERROR_MESSAGE);
            jTn4.setText("");}  
        try{
        nota5 = Double.parseDouble(jTn5.getText());
        }catch (NumberFormatException e){
            errornotas = true;
            errorc5 = "El valor ingresado en el campo 5 no es valido";
        }       
        if (!errorc5.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, errorc5, "Error", JOptionPane.ERROR_MESSAGE);
            jTn5.setText("");}
        if (!errornotas){
        Notas notas = new Notas();
        notas.listaNotas [0] = Double.parseDouble(jTn1.getText());
        notas.listaNotas [1] = Double.parseDouble(jTn2.getText());
        notas.listaNotas [2] = Double.parseDouble(jTn3.getText());
        notas.listaNotas [3] = Double.parseDouble(jTn4.getText());
        notas.listaNotas [4] = Double.parseDouble(jTn5.getText());
        jLpromedio.setText("Promedio:" + notas.calcularPromedio());
        jLdesviacion.setText("Desviacion:" + notas.calcularDesviacion());
        jLnmayor.setText("Nota mayor:" + notas.calcularMayor());
        jLnmenor.setText("Nota menor:" + notas.calcularMenor()); 
        }
    }//GEN-LAST:event_jBcalcularActionPerformed

    private void jTn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTn4ActionPerformed

    }//GEN-LAST:event_jTn4ActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        jTn1.setText("");
        jTn2.setText("");
        jTn3.setText("");
        jTn4.setText("");
        jTn5.setText("");
        jLpromedio.setText("Promedio:");
        jLdesviacion.setText("Desviacion:");
        jLnmayor.setText("Nota mayor:");
        jLnmenor.setText("Nota menor:");
    }//GEN-LAST:event_jBborrarActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBcalcular;
    private javax.swing.JLabel jLdesviacion;
    private javax.swing.JLabel jLn1;
    private javax.swing.JLabel jLn2;
    private javax.swing.JLabel jLn3;
    private javax.swing.JLabel jLn4;
    private javax.swing.JLabel jLn5;
    private javax.swing.JLabel jLnmayor;
    private javax.swing.JLabel jLnmenor;
    private javax.swing.JLabel jLpromedio;
    private javax.swing.JLabel jLtitle;
    private javax.swing.JTextField jTn1;
    private javax.swing.JTextField jTn2;
    private javax.swing.JTextField jTn3;
    private javax.swing.JTextField jTn4;
    private javax.swing.JTextField jTn5;
    // End of variables declaration//GEN-END:variables
}
